const usuariosDemo = [
    {
      id: 104,
      nombre: "Agustin",
      email: "abusscin_@hotmail.com",
      password: "contraseña",
      googleId: "googleIdUsuario",
      imageUrl: "urlImagenUsuario",
      givenName: "Nombre dado",
      admin: true,
      estadoInactividad: false,
      apellido: "Albarracin",
      direccion: "Dirección del Usuario",
      provincia: "Provincia del Usuario",
      localidad: "Localidad del Usuario",
      codigoPostal: "12345",
      dni: "12345678",
      numeroTramite: 222325996,
      telefono: "123456789",
      genero: "Indefinido todavia",
      notificaciones: true
    },
    {
      id: 2224,
      nombre: "Ariel",
      email: "arielg2206@hotmail.com",
      password: "123456",
      googleId: "googleIdUsuario",
      imageUrl: "urlImagenUsuario",
      givenName: "Nombre dado",
      admin: true,
      estadoInactividad: false,
      apellido: "Gonzalez",
      direccion: "corrientes 123",
      provincia: "corrientes",
      localidad: "Localidad del Usuario",
      codigoPostal: "12345",
      dni: "12345678",
      numeroTramite: 222325996,
      telefono: "12223344",
      genero: "Masculino",
      notificaciones: true
    },
    {
      id: 333,
      nombre: "Diego",
      email: "agustin.albarracin22@outlook.com",
      password: "contraseña",
      googleId: "googleIdUsuario",
      imageUrl: "urlImagenUsuario",
      givenName: "Nombre dado",
      admin: undefined,
      estadoInactividad: false,
      apellido: "Maradona",
      direccion: "Dirección del Usuario",
      provincia: "Provincia del Usuario",
      localidad: "Localidad del Usuario",
      codigoPostal: "12345",
      dni: "12345678",
      numeroTramite: 222325996,
      telefono: "123456789",
      genero: "Masculino",
      notificaciones: true
    },
    {
      id: 330,
      nombre: "Milton",
      email: "milthon.g@gmail.com",
      password: "contraseña",
      googleId: "googleIdUsuario",
      imageUrl: "urlImagenUsuario",
      givenName: "Nombre dado",
      admin: true,
      estadoInactividad: false,
      apellido: "Darkox",
      direccion: "Dirección del Usuario",
      provincia: "Provincia del Usuario",
      localidad: "Localidad del Usuario",
      codigoPostal: "12345",  
      dni: "12345678",
      numeroTramite: 222325996,
      telefono: "123456789",
      genero: "Masculino",
      notificaciones: true
    },
    {
      id: 334,
      nombre: "Alejo",
      email: "Alejod951@gmail.com",
      password: "contraseña",
      googleId: "googleIdUsuario",
      imageUrl: "urlImagenUsuario",
      givenName: "Nombre dado",
      admin: true,
      estadoInactividad: false,
      apellido: "Cristian",
      direccion: "Dirección del Usuario",
      provincia: "Provincia del Usuario",
      localidad: "Localidad del Usuario",
      codigoPostal: "12345",  
      dni: "12345678",
      numeroTramite: 222325996,
      telefono: "123456789",
      genero: "Masculino",
      notificaciones: true
    }
  ];
  
  module.exports = usuariosDemo;