export const GET_PRODUCTOS = 'GET_PRODUCTOS';
export const GET_DETAIL = 'GET_DETAIL';
export const GET_NAME = 'GET_NAME';
export const POST_PRODUCTO = 'POST_PRODUCTO';
export const FILTER_PRODUCTO = 'FILTER_PRODUCTO';
export const FILTER_PRODUCTO2 = 'FILTER_PRODUCTO2';
export const GET_ORDER = 'GET ORDER';
export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP';